  - name: Install packages
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - "{{ packages }}"

  - name: Install python-pip
    yum:
      name: python-pip
      state: latest

  - name: check default python version
    shell: "python --version 2>&1 | awk '{print $2}'"
    register: python_installed_version
    changed_when: false

  - name: install python-devel
    yum: name={{ item }}  state=present
    with_items: [ "python-devel", "gcc" ]
    when: python_installed_version.stdout is version_compare('3.0', '<')

  - name: create workdir if doesn`t exist
    file:
      path: "{{ working_directory }}"
      state: directory
      mode: 0755

  - name: render template
    template:
      src: requirements.txt.j2
      dest: "{{ working_directory }}/requirements.txt"

  - name: Install requirements.txt
    pip:
      requirements: "{{ working_directory }}/requirements.txt"
