  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ remote_username }}"
      state: present
      key: "{{ lookup('file', '/home/{{ current_user }}/.ssh/id_rsa.pub') }}"
